version: '3'
services:
    counter:
        image: ale96ct/my-counter-redis-python-nginx:latest
        links:
            - redis
    frontend:
        image: ale96ct/my-frontend:latest
        ports:
            - "8080:80"
        links:
            - counter
    redis:
        image: redis:5-alpine

