version: '3'
services:
    counter:
        image: ale96ct/my-counter-redis-python:latest
        restart: unless-stopped
        links:
            - redis
        ports:
            - "8080:5000"
    redis:
        image: redis:5-alpine

